# Generated by Django 5.2.7 on 2026-08-24 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativemedicine',
            name='alternative_medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine'),
        ),
    ]
