# Generated by Django 5.2.7 on 2026-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='token_number',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('verified', 'Verified'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
