# Generated by Django 5.2.7 on 2026-09-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prescription_token_number_alter_patient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='token_number',
        ),
    ]
