# Generated by Django 5.2.7 on 2026-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_prescription_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='token_number',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
