# Generated by Django 5.2.7 on 2026-09-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='op_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='quantity',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
